services:
  server:
    image: ${DOCKER_TAG}
    restart: always
    environment:
      - MONGO_DB_PATH=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m backend
    ports:
      - '8000:8000'
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/

volumes:
  mongo-data:
   
